In [2]:
import numpy as np

# Matrix addition

In [7]:
%%time

n=2000
matrixA = np.random.randint(0, 100, size=(n, n)) # O(n²)
matrixB = np.random.randint(0, 100, size=(n, n)) # O(n²)

# O(n²)

print("matrix A")
print(matrixA)

print("matrix B")
print(matrixB)

matrix A
[[98 24 23 ...  9 19 41]
 [64 95 73 ... 28 36 39]
 [63 67 61 ... 29 75 71]
 ...
 [43 69 66 ... 20 92 33]
 [25 11 42 ... 91  6 99]
 [43 92  0 ... 91 68 67]]
matrix B
[[82 47  8 ...  0  9 75]
 [64 56  1 ... 29 76 63]
 [ 7 63 43 ... 35 88 38]
 ...
 [17 34 10 ... 10 26 72]
 [41 89 70 ... 61 91 11]
 [94  1 64 ... 75 83 26]]
CPU times: user 93.7 ms, sys: 21.2 ms, total: 115 ms
Wall time: 113 ms


In [8]:
%%time

result = np.zeros((n,n)) # initialize result matrix with zeros

# Add corresponding elements of matrix1 and matrix2
for i in range(n):
    for j in range(n):
        result[i][j] = matrixA[i][j] + matrixB[i][j]
print(result)

[[180.  71.  31. ...   9.  28. 116.]
 [128. 151.  74. ...  57. 112. 102.]
 [ 70. 130. 104. ...  64. 163. 109.]
 ...
 [ 60. 103.  76. ...  30. 118. 105.]
 [ 66. 100. 112. ... 152.  97. 110.]
 [137.  93.  64. ... 166. 151.  93.]]
CPU times: user 2.79 s, sys: 19.5 ms, total: 2.81 s
Wall time: 2.81 s


# Nearest Neighbors

In [9]:
import numpy as np

def nearest_neighbors(data):
    for i in range(len(data)):
        nearest_dist=float('inf')
        nearest_neigh=None
        for j in range(len(data)):
            if i!=j :
                cur_dist=np.sqrt(np.sum((data[i] - data[j]) ** 2))
                if nearest_dist>cur_dist:
                    nearest_dist=cur_dist
                    nearest_neigh=data[j]
        print(f"The nearest neighbor of {data[i]} is {nearest_neigh} dist: {nearest_dist}")

        


In [18]:
n=1000
data = np.random.randint(0, 100, size=(n, 2))
print(data)

[[53 21]
 [94 45]
 [84 74]
 ...
 [89 60]
 [47 91]
 [28 59]]


In [19]:
%%time


nearest_neighbors(data)

# Question: What happens to big O if we don't have 2 coordinates but `n` coordinates ? (high-dimension space)

The nearest neighbor of [53 21] is [52 19] dist: 2.23606797749979
The nearest neighbor of [94 45] is [96 46] dist: 2.23606797749979
The nearest neighbor of [84 74] is [82 71] dist: 3.605551275463989
The nearest neighbor of [ 0 40] is [ 0 38] dist: 2.0
The nearest neighbor of [71 63] is [72 65] dist: 2.23606797749979
The nearest neighbor of [43 60] is [42 59] dist: 1.4142135623730951
The nearest neighbor of [24 14] is [25 15] dist: 1.4142135623730951
The nearest neighbor of [66 78] is [65 76] dist: 2.23606797749979
The nearest neighbor of [97 68] is [96 68] dist: 1.0
The nearest neighbor of [85  9] is [87 10] dist: 2.23606797749979
The nearest neighbor of [53 93] is [54 91] dist: 2.23606797749979
The nearest neighbor of [41 20] is [41 21] dist: 1.0
The nearest neighbor of [77 95] is [77 95] dist: 0.0
The nearest neighbor of [25 24] is [27 24] dist: 2.0
The nearest neighbor of [27 38] is [28 38] dist: 1.0
The nearest neighbor of [81  6] is [80  4] dist: 2.23606797749979
The nearest neigh

The nearest neighbor of [14 71] is [12 71] dist: 2.0
The nearest neighbor of [ 1 24] is [ 0 23] dist: 1.4142135623730951
The nearest neighbor of [ 5 59] is [ 3 58] dist: 2.23606797749979
The nearest neighbor of [28 71] is [28 71] dist: 0.0
The nearest neighbor of [89 69] is [89 71] dist: 2.0
The nearest neighbor of [ 1 53] is [ 6 55] dist: 5.385164807134504
The nearest neighbor of [75 31] is [74 29] dist: 2.23606797749979
The nearest neighbor of [25 19] is [26 20] dist: 1.4142135623730951
The nearest neighbor of [17 87] is [16 87] dist: 1.0
The nearest neighbor of [89 74] is [88 74] dist: 1.0
The nearest neighbor of [69 12] is [69 12] dist: 0.0
The nearest neighbor of [28 68] is [27 68] dist: 1.0
The nearest neighbor of [27 60] is [28 59] dist: 1.4142135623730951
The nearest neighbor of [80 87] is [82 87] dist: 2.0
The nearest neighbor of [13 83] is [12 83] dist: 1.0
The nearest neighbor of [ 3 28] is [ 3 28] dist: 0.0
The nearest neighbor of [87 10] is [85  9] dist: 2.23606797749979
T

The nearest neighbor of [96 25] is [97 24] dist: 1.4142135623730951
The nearest neighbor of [71 34] is [73 34] dist: 2.0
The nearest neighbor of [40 57] is [42 57] dist: 2.0
The nearest neighbor of [65  1] is [66  0] dist: 1.4142135623730951
The nearest neighbor of [88 33] is [87 33] dist: 1.0
The nearest neighbor of [ 6 93] is [ 6 94] dist: 1.0
The nearest neighbor of [ 5 43] is [ 5 42] dist: 1.0
The nearest neighbor of [37 79] is [35 79] dist: 2.0
The nearest neighbor of [24  3] is [23  5] dist: 2.23606797749979
The nearest neighbor of [23  5] is [25  5] dist: 2.0
The nearest neighbor of [17 48] is [17 48] dist: 0.0
The nearest neighbor of [34 79] is [35 79] dist: 1.0
The nearest neighbor of [73 82] is [74 83] dist: 1.4142135623730951
The nearest neighbor of [82 48] is [81 47] dist: 1.4142135623730951
The nearest neighbor of [74 91] is [74 93] dist: 2.0
The nearest neighbor of [88 81] is [90 81] dist: 2.0
The nearest neighbor of [75 10] is [76 13] dist: 3.1622776601683795
The nearest

The nearest neighbor of [41 51] is [41 53] dist: 2.0
The nearest neighbor of [11 36] is [11 34] dist: 2.0
The nearest neighbor of [20 56] is [21 59] dist: 3.1622776601683795
The nearest neighbor of [69 76] is [69 77] dist: 1.0
The nearest neighbor of [41 86] is [42 88] dist: 2.23606797749979
The nearest neighbor of [28  6] is [28  7] dist: 1.0
The nearest neighbor of [96 99] is [96 99] dist: 0.0
The nearest neighbor of [35 15] is [33 14] dist: 2.23606797749979
The nearest neighbor of [59 93] is [58 94] dist: 1.4142135623730951
The nearest neighbor of [49 90] is [51 91] dist: 2.23606797749979
The nearest neighbor of [96 96] is [97 98] dist: 2.23606797749979
The nearest neighbor of [ 2 76] is [ 3 74] dist: 2.23606797749979
The nearest neighbor of [64  0] is [63  0] dist: 1.0
The nearest neighbor of [20 37] is [20 36] dist: 1.0
The nearest neighbor of [90 71] is [89 71] dist: 1.0
The nearest neighbor of [30 57] is [29 58] dist: 1.4142135623730951
The nearest neighbor of [89 64] is [89 64]

The nearest neighbor of [77 82] is [78 84] dist: 2.23606797749979
The nearest neighbor of [51 91] is [49 90] dist: 2.23606797749979
The nearest neighbor of [45 13] is [45 14] dist: 1.0
The nearest neighbor of [ 4 94] is [ 3 93] dist: 1.4142135623730951
The nearest neighbor of [30 29] is [28 29] dist: 2.0
The nearest neighbor of [87 67] is [87 66] dist: 1.0
The nearest neighbor of [50 67] is [51 67] dist: 1.0
The nearest neighbor of [19 73] is [18 73] dist: 1.0
The nearest neighbor of [82 19] is [81 20] dist: 1.4142135623730951
The nearest neighbor of [59 91] is [60 90] dist: 1.4142135623730951
The nearest neighbor of [73 38] is [73 37] dist: 1.0
The nearest neighbor of [64 67] is [65 65] dist: 2.23606797749979
The nearest neighbor of [30 75] is [30 75] dist: 0.0
The nearest neighbor of [57 26] is [58 28] dist: 2.23606797749979
The nearest neighbor of [13 40] is [14 39] dist: 1.4142135623730951
The nearest neighbor of [85 83] is [86 84] dist: 1.4142135623730951
The nearest neighbor of [

The nearest neighbor of [81 83] is [82 85] dist: 2.23606797749979
The nearest neighbor of [ 5 62] is [ 6 64] dist: 2.23606797749979
The nearest neighbor of [74 45] is [72 46] dist: 2.23606797749979
The nearest neighbor of [70 50] is [69 52] dist: 2.23606797749979
The nearest neighbor of [87 21] is [86 21] dist: 1.0
The nearest neighbor of [ 8 64] is [ 7 64] dist: 1.0
The nearest neighbor of [29 53] is [28 53] dist: 1.0
The nearest neighbor of [27 36] is [27 36] dist: 0.0
The nearest neighbor of [23 58] is [24 59] dist: 1.4142135623730951
The nearest neighbor of [72 46] is [74 45] dist: 2.23606797749979
The nearest neighbor of [82 11] is [83 12] dist: 1.4142135623730951
The nearest neighbor of [45 14] is [45 15] dist: 1.0
The nearest neighbor of [51 67] is [51 67] dist: 0.0
The nearest neighbor of [92 30] is [94 31] dist: 2.23606797749979
The nearest neighbor of [67 39] is [67 40] dist: 1.0
The nearest neighbor of [74 83] is [73 82] dist: 1.4142135623730951
The nearest neighbor of [19 1